# Use the official Python image from the Docker Hub
FROM python:3.11.9-alpine

# set work directory
WORKDIR /app

#  Install the required dependencies
RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt


# Instalar psycopg2 para interactuar con PostgreSQL
RUN apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip install psycopg2-binary && \    
    apk --purge del .build-deps && \
    apk add --no-cache ffmpeg

COPY . .
# COPY job /app/job

# Dar permisos de ejecución al script
RUN chmod +x /app/job/process.sh

# celery --app      gevent 
# CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]
CMD ["celery", "-A", "job.celery_app", "worker", "-l", "info", "-P", "gevent"]

